version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - run:
         name: Install Dependencies
         command: |
          npm install
      - run:
         name: Run Tests
         command: |
          npm test
      - run:
         name: Generate Reports
         command: |
          npm run report
      - store_artifacts:
          path: report
workflows:
  build_test:
    jobs:
      - run_tests
